### PR TITLE
fixed the wrongful merge earlier.

### PR DESCRIPTION
**Pull request by yasmiinanon**
Fixed the wrongful merge earlier. Athena's bug fix is included along with the previous script. Tested on my side and works okay!

### CODE REVIEW

**Review by leeathena — APPROVED** [review]

**Review by p11ull — APPROVED** [review]
i think this looks like it works

**Review by beatak777 — APPROVED** [review]
Thanks for fixing this

**Comment by beatak777** [comment]
Although for some reason it says the branch has conflicts and it cannot be merged 🔢

**Comment by leeathena** [comment]
@yasmiinLDN I think we need to review this together to see which set of codes we would like to keep:)

**Pull request merged**
